name: inaugural-address
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pandas=2.3.3
  - numpy=2.3.5
  - bs4=4.14.3
  - requests=2.32.5
  - pytest=9.0.2
  - ipykernel=6.31.0
  - python=3.12 # spacy doesn't support 3.14, gensim doesn't support 3.13
  - spacy=3.8.11
  - pyLDAvis=3.4.0
  - pip=25.3
  - pip:
      - gensim==4.4.0
      - en-core-web-sm==3.8.0
      - afinn==0.1
prefix: /Users/calvin/miniconda3/envs/inaugural-address
