name: inaugural-address
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pandas
  - numpy
  - bs4
  - requests
  - pytest
  - ipykernel
  - python=3.12 # spacy doesn't support 3.14, gensim doesn't support 3.13
  - spacy
  - pyLDAvis
  - pip:
      - gensim==4.4.0
      - en-core-web-sm==3.8.0
      - afinn==0.1
prefix: /Users/calvin/miniconda3/envs/inaugural-address
